### ISSUE TITLE
Dying while running crashes

### ISSUE THREAD

**Issue by millerlarson** [Aidiakapi/adaptive_movement_speed#1]
This was already posted to the mod's [discussions section](https://mods.factorio.com/mod/adaptive_movement_speed/discussion/5e9e57969e85eb000b248d09), but I noticed your preference for GH, so I figure I'd post it here as well.

Was running.  Died.  Rather than prompt, get the following error:
```
The mod Adaptive Movement Speed (0.1.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event adaptive_movement_speed::on_tick (ID 0)
__adaptive_movement_speed__/control.lua:93: attempt to index local 'character' (a nil value)
stack traceback:
__adaptive_movement_speed__/control.lua:93: in function <__adaptive_movement_speed__/control.lua:56>
```

Thank you again for your great mods!

**Comment by Aidiakapi** [comment]
Thanks for letting me know! I've fixed it now :).
